version: '3.8'

networks:
  iceberg_net:
    driver: bridge    

services:
  spark-iceberg:
    image: spark-iceberg
    container_name: spark-iceberg
    profiles: [default]
    build: ./spark
    networks:
      - iceberg_net
    depends_on:
      - hive
      - minio
    volumes:
      - ./spark/notebooks:/home/iceberg/notebooks
      - ./spark/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf:r
      - ./spark/hive-site.xml:/opt/spark/conf/hive-site.xml:r
    environment:
      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: password
      AWS_REGION: us-east-1
    ports:
      - 8888:8888 #jupyter nodebook port
      - 8080:8080 #Spark-UI port
      - 18080:18080 #history server port
      - 4040:4040 #application spark-ui
      - 4041:4041 #application spark-ui
      - 8081:8081 #log urls
  mysql:
    image: mysql
    hostname: mysql
    profiles: [default]
    container_name: mysql
    ports:
      - 3306:3306  # default MySQL port
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: metastore_db
    networks:
      - iceberg_net
  
  hive:
    image: hive-hms
    build: ./hive-metastore
    profiles: [default]
    hostname: hive-metastore
    container_name: hive-metastore
    ports:
      - 9083:9083
    volumes:
      - ./hive-metastore/metastore-site.xml:/opt/apache-hive-metastore-3.0.0-bin/conf/metastore-site.xml:r
    environment:
      DB_HOSTNAME: mysql
#      SKIP_SCHEMA_INIT: false
    depends_on:
      - mysql
    networks:
      - iceberg_net

  minio:
    image: minio/minio
    hostname: minio
    profiles: [default]
    container_name: minio
    ports:
      - 9090:9090 # endpoint port
      - 8443:9091 # minio web-ui
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
      MINIO_DOMAIN: minio
    command: server --address ":9090" --console-address ":9091" /data
    networks:
      - iceberg_net

  mc:
    depends_on:
      - minio
    image: minio/mc
    profiles: [setup]
    container_name: mc
    networks:
      iceberg_net:
    environment:
      AWS_ACCESS_KEY_ID: admin
      AWS_SECRET_ACCESS_KEY: password
      AWS_REGION: us-east-1
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add minio http://minio:9090 admin password) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb --ignore-existing minio/warehouse;
      /usr/bin/mc policy set public minio/warehouse;
      /usr/bin/mc mb --ignore-existing minio/spark-events/logs;
      /usr/bin/mc policy set public minio/spark-events/logs;
      tail -f /dev/null
      "
volumes:
  minio_data:
  mysql_data: